USE master
GO

IF NOT EXISTS(SELECT 1 FROM sys.databases WHERE name = 'EfCoreMWE')
CREATE DATABASE EfCoreMWE
GO

USE EfCoreMWE
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Foos')
DROP TABLE Foos
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Bars')
DROP TABLE Bars

CREATE TABLE Bars (
	BarId int NOT NULL IDENTITY,
	Baz nvarchar(max),
	CONSTRAINT PK_Bars PRIMARY KEY NONCLUSTERED (BarId)
)

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Foos')
CREATE TABLE Foos (
	FooId int NOT NULL IDENTITY,
	Bar_BarId int NOT NULL,
	Qux nvarchar(max),
	CONSTRAINT PK_Foos PRIMARY KEY NONCLUSTERED (FooId),
	CONSTRAINT FK_Foo_Bar FOREIGN KEY (Bar_BarId) REFERENCES Bars(BarId)
)

INSERT INTO Bars (Baz) VALUES ('The baz of the bar')
INSERT INTO Foos (Bar_BarId, Qux) VALUES (@@IDENTITY, 'The Qux of the foo')

