// <auto-generated />
using EFCoreOnExistingDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EFCoreOnExistingDb.Migrations
{
    [DbContext(typeof(MweDbContext))]
    [Migration("20171212100647_MigrateToEfCore")]
    partial class MigrateToEfCore
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCoreOnExistingDb.Entities.Bar", b =>
                {
                    b.Property<long>("BarId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Baz")
                        .IsRequired();

                    b.HasKey("BarId");

                    b.ToTable("Bars");
                });

            modelBuilder.Entity("EFCoreOnExistingDb.Entities.Foo", b =>
                {
                    b.Property<long>("FooId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("BarId");

                    b.Property<string>("Qux")
                        .IsRequired();

                    b.HasKey("FooId");

                    b.HasIndex("BarId");

                    b.ToTable("Foos");
                });

            modelBuilder.Entity("EFCoreOnExistingDb.Entities.Foo", b =>
                {
                    b.HasOne("EFCoreOnExistingDb.Entities.Bar", "Bar")
                        .WithMany()
                        .HasForeignKey("BarId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
